import pg from 'pg';
const { Pool } = pg;
const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const q = async (sql) => (await pool.query(sql)).rows;
console.log('products:', (await q('select count(*)::int n from products'))[0].n);
console.log('active:', (await q("select id from products where active = true order by id")).map(r => r.id).join(' '));
console.log('holiday cactus present:', (await q("select count(*)::int n from products where id like '%P%006%'"))[0].n);
console.log('care_guides:', (await q('select count(*)::int n from care_guides'))[0].n);
console.log('has schedule col:', (await q("select count(*)::int n from information_schema.columns where table_name='order_window' and column_name='schedule'"))[0].n);
await pool.end();
